### ISSUE TITLE
The \mid glyph, and strange behavior of : and \colon

### ISSUE THREAD

**Issue by RuixiZhang42** [Stone-Zeng/FiraMath#15]
According to [Issue&nbsp;2](https://github.com/Stone-Zeng/FiraMath/issues/2), `\parallel` is not yet available (as of today), and neither is&nbsp;`\mid`. However, according to [`fontdef.dtx`](http://mirrors.ctan.org/macros/latex/base/fontdef.dtx):

    \DeclareMathSymbol{\parallel}{\mathrel}{symbols}{"6B}
    \DeclareMathSymbol{\mid}{\mathrel}{symbols}{"6A}
    \DeclareMathDelimiter{\Vert}
       {\mathord}{symbols}{"6B}{largesymbols}{"0D}
    \DeclareMathDelimiter{\vert}
       {\mathord}{symbols}{"6A}{largesymbols}{"0C}

suggesting that the `\parallel` and&nbsp;`\mid` commands point to the same corresponding glyph of&nbsp;`\Vert` and&nbsp;`\vert`, respectively. Nevertheless, using `unicode-math` yields missing glyph. Is&nbsp;it possible to simply “steal” the existing glyph of&nbsp;`\Vert` and&nbsp;`\vert`, and be done with&nbsp;`\parallel` and&nbsp;`\mid`?

Furthermore, it seems that&nbsp;`:` and&nbsp;`\colon` won’t show up *unless* one specifies option&nbsp;`colon=literal` to the package&nbsp;`unicode-math`. But `colon=literal` changes the spacing of&nbsp;`:`.

    % Compiled with XeLaTeX or LuaLaTeX
    \documentclass{article}
    \usepackage{amsmath}
    \let\amsmathcolon\colon
    \usepackage[sfdefault]{FiraSans}
    \usepackage[mathrm=sym]{unicode-math}% colon=literal
    \setmathfont{Fira Math}% FiraMath v0.2.2
    \renewcommand*\colon{\mathpunct{:}}
    
    \begin{document}
    $a : b$, $a \amsmathcolon b$, $a \mid b$, $a \parallel b$
    
    $a : b$, $a \colon b$, $a \mathrel{\vert} b$, $a \mathrel{\Vert} b$
    \end{document}

Output for default colon behavior or&nbsp;`colon=TeX`:

![colon=TeX](https://user-images.githubusercontent.com/39968857/45510612-b4a51680-b768-11e8-8646-77f8226ec98f.png)

Output for&nbsp;`colon=literal`:

![colon=literal](https://user-images.githubusercontent.com/39968857/45510633-c5558c80-b768-11e8-9552-54913d0bc66d.png)

**Comment by RuixiZhang42** [comment]
The&nbsp;`:` and&nbsp;`\colon` issue seems to be caused by the following in&nbsp;[`um-code-main.dtx`](http://mirrors.ctan.org/macros/latex/contrib/unicode-math/um-code-main.dtx):

    \bool_if:NF \g_@@_literal_colon_bool
      {
        \@@_remap_symbol:nnn {`\:} {\mathrel} {"02236}% colon to ratio (i.e., punct to rel)
      }

Since the Unicode character “ratio” (U+2236) was not available in FiraMath&nbsp;v0.2.2, using the default colon setting (or equivalently, `colon=TeX`) would produce the .notdef glyph, as expected.

A quick fix with FiraMath&nbsp;v0.2.2 would be

    % Compiled with XeLaTeX or LuaLaTeX
    \documentclass{article}
    \usepackage[mathrm=sym]{unicode-math}
    \setmathfont{Fira Math}% FiraMath v0.2.2
    \AtBeginDocument{%
      \DeclareMathSymbol{:}{\mathrel}{operators}{"3A}%
    }
    
    \begin{document}
    Colons fixed:
    $a : b$, $a \colon b$
    \end{document}

Since “ratio” is used rather commonly (e.g., `$\{x:x>0\}$`), and since `\colon` is based on&nbsp;`:`, I&nbsp;really hope this character will be available in the next pre-release.

**Comment by stone-zeng** [comment]
I have simply added these glyphs.

Note that `:`, `\colon`, `\mathcolon` and `\mathratio` all use `U+2236`, and `U+003C` is actually inaccessible (see <https://tex.stackexchange.com/q/450836/136923>, but still no answer when I add this comment).
