### ISSUE TITLE
All build artifacts are expired

### ISSUE THREAD

**Issue by rnhmjoj** [Stone-Zeng/FiraMath#68]
It's not possible to download any recent version of firamath because all the build artifacts are expired.
Can you make a proper release or distribute them elsewhere?

**Comment by ArchangeGabriel** [comment]
What do you mean? Downloading the .otf from e.g. https://github.com/firamath/firamath/releases/tag/v0.3.4 works for me.

**Comment by rnhmjoj** [comment]
I mean this section: https://github.com/firamath/firamath#development-builds

v0.3.4 is the latest released version, but is old and doesn't contain all the weight variants.

**Comment by rnhmjoj** [comment]
If anyone needs it, here's a build of 86cce9463be15508bbdc36bf1a97689a736283dc: [firamath.zip](https://github.com/firamath/firamath/files/7612200/firamath.zip)

**Comment by stone-zeng** [comment]
Sorry. I have re-enabled the github actions for the working branch, and you can download the latest dev build again. Note that this is still a work in progress, so it may contain unfinished things or bugs.
