### ISSUE TITLE
encoding of phi and varphi

### ISSUE THREAD

**Issue by MichaelSaunders5** [Stone-Zeng/FiraMath#72]
I think you have mixed up the traditional (closed) form of phi with its variant (open) form.
ϕ  should be encoded 03C6; φ should be at 03D5.

**Comment by stone-zeng** [comment]
According to Unicode code chart:

<img width="953" alt="Screen Shot 2022-04-26 at 14 23 23" src="https://user-images.githubusercontent.com/18233088/165235119-41b68eb0-4b17-4a53-916c-44815eeb235e.png">

So I think in Fira Math the following mapping is correct:

<img width="249" alt="Screen Shot 2022-04-26 at 14 24 18" src="https://user-images.githubusercontent.com/18233088/165235247-1c406e5d-728e-4344-9b7e-5ce85083a173.png">
